files:
  click:
    src: audio/click.ogg
  qiuci:
    src: music/qiucimusic.mp3
options:
  volume: 0.5
  musicFadeInTime: 0.5
  musicFadeInDelay: 0.5
  musicFadeOutTime: 0.5
audioTriggers:
  onPlayerAnswered: click
