---
gameTitle: 丝路汉韵——重走丝绸之路，传承非遗文化
saveFileName: 丝路汉韵
images: {}
dialogPanel:
  textSpeed: 30
  animateText: true
  timeBetweenLines: 100
  overlayMode: true
  rightOffset: 100
  bottomOffset: 50
  width: 475
  height: 680
layout:
  backgrounds:
    width: 1280
    height: 720
  dialogBottomPadding: 70
  mobileDialogHeightPercentage: 60
  verticalLayoutThreshold: 600
  portraits:
    width: 100
    height: 100
notifications:
  timeOnScreen: 2.5
  alsoPrintInDialogue: true
hudStats: {}
interactionTags:
  default:
    onlyInteractOutsideOfScripts: true
menuButtons: {}
saves:
  mode: manual
  slots: 10
